Climber changes during Sac Day 1
DeepBlueRobotics/RobotCode2019 pull request #105
Opened 2019-03-22 07:14 UTC by kevinzwang

2019-03-22 13:46 UTC, brettle requested changes

2019-03-22 13:46 UTC, brettle commented on Robot2019/src/main/java/frc/robot/commands/NormalDrive.java
> +public class NormalDrive extends InstantCommand {
This should really be renamed something like ToggleCharDrive.

2019-04-27 02:31 UTC, kevinzwang commented
slow climb was never used and is now obsolete because we have a software limit to our climber elevator

2019-04-27 02:37 UTC, kevinzwang commented
but we should make these aesthetic changes in another pull request

2019-04-27 19:47 UTC, brettle approved these changes

2019-04-27 19:50 UTC, brettle commented
@kevinzwang, I've approved, so you should be able to merge now if you feel it's ready.

2019-05-17 17:13 UTC, merged